apiVersion: v1
kind: Service
metadata:
  name: weather-app-service
spec:
  selector:
    app: weather-app
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer


# Old Service:
# apiVersion: v1
# kind: Service
# metadata:
  # name: weather-app-service
# spec:
  # selector:
    # app: weather-app
  # ports:
    # - port: 80
      # targetPort: 3000
  # type: ClusterIP
